### ISSUE TITLE
Android 8.0 报错:/system/build.prop (Permission denied)

### ISSUE THREAD

**Issue by monty8800** [BuglyDevTeam/Bugly-Android-Demo#66] opened 2018-05-22 07:06 UTC
#### 异常类型

运行时异常

#### 手机型号

Android8.0模拟器

#### 手机系统版本

Android8.0模拟器

#### 系统

mac

#### 堆栈/日志

05-22 07:01:27.544 25432-25473/com.rlzz.wms W/CrashReport: server native changed to true
05-22 07:01:27.545 25432-25473/com.rlzz.wms W/CrashReport: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.rlzz.wms-tfoCJqhfNPmG--4pVsxIHQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.rlzz.wms-tfoCJqhfNPmG--4pVsxIHQ==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libBugly.so"
05-22 07:01:27.545 25432-25473/com.rlzz.wms W/CrashReport: [Native] Failed to load so: Bugly
05-22 07:01:27.592 25432-25474/com.rlzz.wms W/CrashReport: java.io.FileNotFoundException: /system/build.prop (Permission denied)
                                                               at java.io.FileInputStream.open0(Native Method)
                                                               at java.io.FileInputStream.open(FileInputStream.java:200)
                                                               at java.io.FileInputStream.<init>(FileInputStream.java:150)
                                                               at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                               at java.io.FileReader.<init>(FileReader.java:58)
                                                               at com.tencent.bugly.crashreport.common.info.b.q(BUGLY:320)
                                                               at com.tencent.bugly.crashreport.common.info.b.a(BUGLY:379)
                                                               at com.tencent.bugly.crashreport.common.info.a.r(BUGLY:509)
                                                               at com.tencent.bugly.proguard.a.a(BUGLY:160)
                                                               at com.tencent.bugly.crashreport.biz.a.c(BUGLY:271)
                                                               at com.tencent.bugly.crashreport.biz.a.a(BUGLY:35)
                                                               at com.tencent.bugly.crashreport.biz.a$2.run(BUGLY:335)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                               at java.lang.Thread.run(Thread.java:764)
05-22 07:01:27.617 25432-25474/com.rlzz.wms W/CrashReport: no READ_PHONE_STATE permission to get IMEI
05-22 07:01:27.618 25432-25474/com.rlzz.wms W/CrashReport: no READ_PHONE_STATE permission to get IMSI

**Comment by feng88724** [comment] 2018-09-07 10:29
华为P9，真机，遇到同样问题

**Comment by JalenChen** [comment] 2019-01-23 03:02
Duplicate of #92

**Closed by JalenChen** 2019-01-23 03:02 UTC

**Comment by uessless** [comment] 2019-07-22 03:02
我遇到了同样的问题
